<a href="https://colab.research.google.com/github/ptliam-tech/test-colab/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello world')

Hello world


In [1]:
import numpy as np
arr = np.zeros(shape=(5, 5), dtype='int16')
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
