<a href="https://colab.research.google.com/github/ptliam-tech/test-colab/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello world')

Hello world


In [1]:
import numpy as np
arr = np.zeros(shape=(5, 5), dtype='int16')
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
arr = np.ones(shape=(10, 10), dtype='float32') * 8
print(arr)

[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [4]:
arr = np.full(shape=(10, 10), fill_value=8, dtype='float32')
print(arr)

[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [5]:
arr = np.arange(0, 15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Từ mảng 1 chiều thành mảng 2 chiều 9 hàng 10 cột

In [10]:
arr = np.arange(10, 100).reshape(9,10)
print(arr)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


*np.eye(N, M=None, k=0)*  
- Tham số:
  - N: số hàng  
  - M: số cột (mặc định = N → ma trận vuông)  
  - k: đường chéo chính:  
      - 0: đường chéo chính  
      - \>0: dịch lên trên  
      - <0: dịch xuống dưới  

In [13]:
arr = np.eye(N=8, dtype='int16')
print(arr)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [15]:
arr = np.array(
    [
      [
          [4, 5, 4, 2],
          [6, 3, 5, 1],
          [5, 2, 1, 2],
      ],
      [
          [7, 2, 3, 1],
          [6, 2, 0, 9],
          [0, 1, 9, 1],
      ]
    ]
)
print(arr)

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]


In [18]:
arr = np.array(
    [
        ['4', '3', '6', '2', '1'],
        ['7', '2', '1', '2', '6'],
    ],
    dtype='<U1',
)
print(arr)
arr = arr.astype('float16')
print(arr)

[[4 3 6 2 1]
 [7 2 1 2 6]]
[[4. 3. 6. 2. 1.]
 [7. 2. 1. 2. 6.]]


In [19]:
arr = np.array([1,2,3,4,5], dtype='<U1')
print(arr)

['1' '2' '3' '4' '5']
